### ISSUE TITLE
Add this to MAT when enabling MAT in existing (winforms) project

### ISSUE THREAD

**Issue by wstaelens** [TheMATDude/ResourceToXliff#2]
Existing winforms solution with lots of .resx translations.

when you enable MAT for the first time, push the resx data to .xlf (+ translations).
Because currently existing translations will be lost in MAT.

**Comment by TheMATDude** [comment]
This is being investigated.  Feel free to also upvote on the MAT user voice site on the same request: https://multilingualapptoolkit.uservoice.com/forums/231158-general/suggestions/17382832-the-toolkit-should-not-override-resw-files-that-ex

**Comment by wstaelens** [comment]
@TheMATDude any news on this?

**Comment by TheMATDude** [comment]
The latest version of MAT has been updated to preserve the previous translations.  This happens automatically when an existing language is selected via the Add Translation Languages menu.  The translation are moved into the XLIFF file and the target language resource files.

**Comment by wstaelens** [comment]
@TheMATDude do you mean this version:
Date published: Feb 21, 2018
Version: v4.0.6900.0 (For Visual Studio 2017)

?
So hundred of existing .resx translations for winforms will not be thrown away?

**Comment by TheMATDude** [comment]
> @TheMATDude do you mean this version:
> Date published: Feb 21, 2018
> Version: v4.0.6900.0 (For Visual Studio 2017)
> 
> ?
> So hundred of existing .resx translations for winforms will not be thrown away?

Must have the latest release from the Marketplace (VS 2017: 4.0.6900.0). I tested it myself :-) 

I used multiple same target language resource files in a project, enabling MAT and added XLF support for the languages with existing resource files contains translations.  I used a compare tool, I did not discover any lost translations.  If you find any issue, please let me know asap.

The status will be 'Needs review' when the source and target are the same text and 'Translated' when they are different.  If a resource is marked as new, it did not exist in the original target resource file.  (Note: 'Needs Review' is used in cases there it is not practical to determine if the target resource was not translated or if the translated text is the same as the source text)

See [Multilingual App Toolkit v4.0 change log](https://multilingualapptoolkit.uservoice.com/knowledgebase/articles/460620) for details
