### ISSUE TITLE
VS2017Pro

### ISSUE THREAD

**Issue by bobbytait** [TheMATDude/ResourceToXliff#3]
In case anyone needs assistance setting this up in VS2017. Am using Pro v15.4.5.

Installed MAT 4.0.6810.0.

Had to point the references for Microsoft.Multilingual.Utilities.dll & Microsoft.Multilingual.XLiff.dll to C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Multilingual App Toolkit\v4.0.

Had to remove reference to Microsoft.Multilingual.Markup.dll, as it does not exist in the MAT directory tree.

Had to update application's Target Framework from .NET Framework 4.5.2 to 4.6.2.

Then it compiles.

**Comment by dpaulino** [comment]
For VS2019 16.8.1, I just updated the target framework from 4.5.2 to 4.8 and the build succeeded. I didn't make any other changes.

**Comment by TheMATDude** [comment]
I update the framework in the repo.
